src/Entity/Article.php
<?php

namespace App\Entity;

use DateTime;
use App\Entity\Img;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article implements Translatable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      minMessage = "S'il te plait, rentre au moins {{ limit }} caractères."
     * )
     */
    private $title;

    /**
     * @ORM\Column(length=128, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Gedmo\Translatable
     */
    private $text;

    /**
     * @Gedmo\Locale
     */
    private $locale;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_event;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $format;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    
    /**
     * 
     * @ORM\OneToMany(targetEntity="App\Entity\Img", mappedBy="article", cascade={"persist", "remove"})
     */
    private $imgs;

    /**
     * @Assert\All({
     *      @Assert\Image(mimeTypes="image/*")
     * })
     */
    private $imgsFile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users")
     */
    private $modified_by;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $api_data = [];

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SocialNetwork", mappedBy="article", cascade={"persist", "remove"})
     * @Assert\Type(type="App\Entity\SocialNetwork")
     * @Assert\Valid
     */
    private $socialNetwork;

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $youtube = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $facebook = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $vimeo = [];

    public function __construct()
    {
        $this->created_at = new DateTime();
        $this->imgs = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function setTranslatableLocale($locale)
    {
        $this->locale = $locale;

        return $this;
    }

    public function getDateEvent(): ?\DateTimeInterface
    {
        return $this->date_event;
    }

    public function setDateEvent(?\DateTimeInterface $date_event): self
    {
        $this->date_event = $date_event;

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(string $format): self
    {
        $this->format = $format;
        
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Img[]|null
     */
    public function getImgs()
    {
        return $this->imgs;
    }

    public function addImg(Img $img): self
    {
        if (!$this->imgs->contains($img)) {
            $this->imgs[] = $img;
            $img->addArticle($this);
        }

        return $this;
    }

    public function removeImg(Img $img): self
    {
        if ($this->imgs->contains($img)) {
            $this->imgs->removeElement($img);
            $img->removeArticle($this);
        }
        return $this;
    }

    /**
    * @return mixed
    */
    public function getImgsFile()
    {
        return $this->imgsFile;
    }
    
    /**
     * @param mixed $imgsFile
     * @return Article
     */
    public function setImgsFile($images): self
    {
        foreach($images as $image)
        {
            $img = new Img();
            $img->setImgData($image);
            $this->addImg($img);
        }
        return $this;
    }
    
    public function getUser() 
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getModifiedBy(): ?Users
    {
        return $this->modified_by;
    }

    public function setModifiedBy(?Users $modified_by): self
    {
        $this->modified_by = $modified_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getApiData(): ?array
    {
        return $this->api_data;
    }

    public function setApiData(?array $api_data): self
    {
        $this->api_data = $api_data;

        return $this;
    }

    public function getSocialNetwork(): ?SocialNetwork
    {
        return $this->socialNetwork;
    }

    public function setSocialNetwork(?SocialNetwork $socialNetwork): self
    {
        $this->socialNetwork = $socialNetwork;

        // set (or unset) the owning side of the relation if necessary
        $newArticle = null === $socialNetwork ? null : $this;
        if ($socialNetwork->getArticle() !== $newArticle) {
            $socialNetwork->setArticle($newArticle);
        }

        return $this;
    }

    public function getYoutube(): ?array
    {
        return $this->youtube;
    }

    public function setYoutube(?array $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getFacebook(): ?array
    {
        return $this->facebook;
    }

    public function setFacebook(?array $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getVimeo(): ?array
    {
        return $this->vimeo;
    }

    public function setVimeo(?array $vimeo): self
    {
        $this->vimeo = $vimeo;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @UniqueEntity(
 *      fields = {"mail"},
 *      message = "Cette adresse mail a déjà été enregistré"
 * )
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;
    
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email()
     */
    private $mail;
    
    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(
     *      min = 8,
     *      minMessage = "Le mot de passe doit avoir au minimum {{ limit }} caractères"
     * )
     */
    private $password;
    
    /**
     * @Assert\EqualTo(propertyPath="password", message="Le mot de passe n'est pas identique")
     */
    public $confirm_password;

    public $reset_password;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="user")
     */
    private $articles;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_log;

    private $rgpd;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }
    
    public function __toString()
    {
        return $this->surname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->mail;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_MEMBER
        $roles[] = 'ROLE_MEMBER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getConfirmPassword(): string
    {
        return (string) $this->confirm_password;
    }
    
    public function getResetPassword(): string
    {
        return (string) $this->reset_password;
    }

    public function setResetPassword(string $rawPassword): self
    {
        $this->reset_password = $rawPassword;
        
        return $this;
    }
    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        $this->reset_password = null;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLastLog(): ?\DateTimeInterface
    {
        return $this->last_log;
    }

    public function setLastLog(\DateTimeInterface $last_log): self
    {
        $this->last_log = $last_log;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getRgpd()
    {
        return $this->rgpd;
    }

    public function setRgpd($rgpd): self
    {
        $this->rgpd = $rgpd;

        return $this;
    }
}

templates/include/contactForm.html.twig
<div id="contact_form" class="form-group">
    <h2 class="subtitle">{% trans %}contact form{% endtrans %}</h2>
    {{ form_start(form) }}
        <div class="form-group">
            {{ form_errors(form.surname) }}
            {{ form_widget(form.surname) }}
            {{ form_label(form.surname, null, {"label_attr": {"class": "moving-label"}}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.name) }}
            {{ form_widget(form.name) }}
            {{ form_label(form.name, null, {"label_attr": {"class": "moving-label"}}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.email) }}
            {{ form_widget(form.email) }}
            {{ form_label(form.email, null, {"label_attr": {"class": "moving-label"}}) }}
        </div>
        {{ form_errors(form.text) }}
        {{ form_row(form.text) }}
        
        {{ form_row(form.send) }}
    {{ form_end(form) }}
</div>

templates/include/datetimeArticle.html.twig
<div id="datetime_article">
    <p class="onelinetxt">{% trans %}Créé le{% endtrans %} {{ article.createdAt|date("d/m/Y - H:i:s", "Europe/Paris") }} {% trans %}par{% endtrans %} {{ article.user.surname }}</p>
    {% if article.modifiedBy != '' %}
    <p class="onelinetxt">{% trans %}Modifié le{% endtrans %} {{ article.updatedAt|date("d/m/Y - H:i:s", "Europe/Paris") }} {% trans %}par{% endtrans %} {{ article.modifiedBy.surname }}</p>
    {% endif %}
</div>

templates/include/facebookPlayer.html.twig
<script async defer src="https://connect.facebook.net/fr_FR/sdk.js"></script>
<script>
	window.fbAsyncInit = function () {
        FB.init({
            appId: '670409820405312',
            xfbml: true, 
            version: 'v7.0'
            });

        // Get Embedded Video Player API Instance
        var my_video_player;
        FB.Event.subscribe('xfbml.render', function(msg) {
            console.log(msg);
            if (msg.type === 'video') {
            my_video_player = msg.instance;
            }
        });
    };

{% for video in videos %}
document.getElementById('fbplayer[{{ loop.index0 }}]').setAttribute('data-href', "{{video}}");
{% endfor %}
</script>

templates/include/htmlMeta.html.twig
<title>CDLM.space - {{titleArticle}}</title>
<!-- Primary Meta Tags -->
<meta name="title" content="CDLM.space - {{ titleArticle }}">
<meta name="description" content="{{ descriptionArticle }}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="article">
<meta property="og:url" content="{{app.request.uri}}">
<meta property="og:title" content="CDLM.space - {{ titleArticle }}">
<meta property="og:description" content="{{ descriptionArticle }}">
<meta property="og:image" content="{{ coverArticle }}">
<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" />

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="{{app.request.uri}}">
<meta property="twitter:title" content="CDLM.space - {{ titleArticle }}">
<meta property="twitter:description" content="{{ descriptionArticle }}">
<meta property="twitter:image" content="{{ coverArticle }}">

templates/include/soundcloudPlayerJs.html.twig
<script src="https://connect.soundcloud.com/sdk/sdk-3.3.2.js"></script>
<script>
{% for sound in sounds %}
fetch("https://soundcloud.com/oembed?url={{ sound }}&format=json&iframe=false", {
    method: 'GET',
})
.then(response => response.json())
.then(data => {
    let track_id = data.html.match(/tracks%2F[0-9]+/)[0].match(/[0-9]{9}/)[0];
    document.getElementById("sound[{{ loop.index0 }}]").innerHTML = '<iframe width="100%" height="20" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/' + track_id + '&color=%230e0d26&inverse=true&auto_play=false&show_user=true"></iframe>';
});
{% endfor %}
</script>

templates/include/vimeoPlayer.html.twig
<script src="https://player.vimeo.com/api/player.js"></script>
<script>
{% for video in videos %}
{# document.getElementById("vimeoplayer[{{ loop.index0 }}]").innerHTML = "<div width='400' height='400' data-vimeo-url='{{ video }}'></div>"; #}
(new Vimeo.Player("vimeoplayer[{{ loop.index0 }}]", {
    url: "{{ video }}",
}));

{% endfor %}
</script>

templates/include/youtubePlayer.html.twig
<script src="https://www.youtube.com/iframe_api"></script>
<script>
    let videos = [];
    {% for video in videos %}
    videos.push("{{video}}");
    {% endfor %}
    let youtubePlayer;
    function onYouTubeIframeAPIReady() {
        for (let i=0; i < videos.length; i++){
            youtubePlayer = new YT.Player('player[' + i + ']', {
                videoId: youtube_parser(videos[i]),
                playerVars: {
                    'autoplay': false,
                    'rel': 0,
                    'showinfo': 0,
                    'color': 'white',
                    'cc_load_policy': 0,
                },
            });
        }
    }

    function youtube_parser(url) {
        const regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
        let match = url.match(regExp);
        return (match && match[7].length == 11) ? match[7] : false;
    };
</script>