src/Entity/Article.php
<?php

namespace App\Entity;

use DateTime;
use App\Entity\Img;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article implements Translatable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      minMessage = "S'il te plait, rentre au moins {{ limit }} caractères."
     * )
     */
    private $title;

    /**
     * @ORM\Column(length=128, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Gedmo\Translatable
     */
    private $text;

    /**
     * @Gedmo\Locale
     */
    private $locale;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_event;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $format;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    
    /**
     * 
     * @ORM\OneToMany(targetEntity="App\Entity\Img", mappedBy="article", cascade={"persist", "remove"})
     */
    private $imgs;

    /**
     * @Assert\All({
     *      @Assert\Image(mimeTypes="image/*")
     * })
     */
    private $imgsFile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users")
     */
    private $modified_by;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $api_data = [];

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\SocialNetwork", mappedBy="article", cascade={"persist", "remove"})
     * @Assert\Type(type="App\Entity\SocialNetwork")
     * @Assert\Valid
     */
    private $socialNetwork;

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $youtube = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $facebook = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     * @Assert\All({
     *      @Assert\Url(
     *          message = "l'url {{ value }} n'est pas valide",
     *      )
     * })
     */
    private $vimeo = [];

    public function __construct()
    {
        $this->created_at = new DateTime();
        $this->imgs = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function setTranslatableLocale($locale)
    {
        $this->locale = $locale;

        return $this;
    }

    public function getDateEvent(): ?\DateTimeInterface
    {
        return $this->date_event;
    }

    public function setDateEvent(?\DateTimeInterface $date_event): self
    {
        $this->date_event = $date_event;

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(string $format): self
    {
        $this->format = $format;
        
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Img[]|null
     */
    public function getImgs()
    {
        return $this->imgs;
    }

    public function addImg(Img $img): self
    {
        if (!$this->imgs->contains($img)) {
            $this->imgs[] = $img;
            $img->addArticle($this);
        }

        return $this;
    }

    public function removeImg(Img $img): self
    {
        if ($this->imgs->contains($img)) {
            $this->imgs->removeElement($img);
            $img->removeArticle($this);
        }
        return $this;
    }

    /**
    * @return mixed
    */
    public function getImgsFile()
    {
        return $this->imgsFile;
    }
    
    /**
     * @param mixed $imgsFile
     * @return Article
     */
    public function setImgsFile($images): self
    {
        foreach($images as $image)
        {
            $img = new Img();
            $img->setImgData($image);
            $this->addImg($img);
        }
        return $this;
    }
    
    public function getUser() 
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getModifiedBy(): ?Users
    {
        return $this->modified_by;
    }

    public function setModifiedBy(?Users $modified_by): self
    {
        $this->modified_by = $modified_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getApiData(): ?array
    {
        return $this->api_data;
    }

    public function setApiData(?array $api_data): self
    {
        $this->api_data = $api_data;

        return $this;
    }

    public function getSocialNetwork(): ?SocialNetwork
    {
        return $this->socialNetwork;
    }

    public function setSocialNetwork(?SocialNetwork $socialNetwork): self
    {
        $this->socialNetwork = $socialNetwork;

        // set (or unset) the owning side of the relation if necessary
        $newArticle = null === $socialNetwork ? null : $this;
        if ($socialNetwork->getArticle() !== $newArticle) {
            $socialNetwork->setArticle($newArticle);
        }

        return $this;
    }

    public function getYoutube(): ?array
    {
        return $this->youtube;
    }

    public function setYoutube(?array $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getFacebook(): ?array
    {
        return $this->facebook;
    }

    public function setFacebook(?array $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getVimeo(): ?array
    {
        return $this->vimeo;
    }

    public function setVimeo(?array $vimeo): self
    {
        $this->vimeo = $vimeo;

        return $this;
    }
}

src/Controller/HomePublicController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ArticleRepository;
use App\Repository\ImgRepository;
use App\Repository\UsersRepository;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class HomePublicController extends AbstractController
{
    private $article;
    private $security;
    private $users;
    private $imgRepo;
    
    public function __construct(Security $security, UsersRepository $users, ArticleRepository $article, ImgRepository $imgRepo)
    {
        $this->security = $security;
        $this->article = $article;
        $this->users = $users;
        $this->imgRepo = $imgRepo;
    }

    /**
     * @Route("/")
     */
    public function localRedirect()
    {
        return $this->redirectToRoute('home_public');
    }

    /**
     * @Route("/{_locale}/", name="home_public", requirements={"_locale": "fr|en"})
     */
    public function index()
    {
        if ($this->security->getUser() !== null) {
            $articles = $this->article->findAllDESC();
        } else {
            $articles = $this->article->takeAllExceptprivateEvent();
        }

        $covers = $this->getCovers($articles);
        return $this->render('home_public/index.html.twig', [
            'articles' => $articles,
            'covers' => $covers,
        ]);
    }

    /**
     * @Route("/{_locale}/article/{format}", requirements={"_locale": "fr|en"}, name="articles", methods={"GET"})
     */
    public function articles(Request $request)
    {
        $format = $request->get('format');
        $articles = $this->article->findAllByformat($format);
        $covers = $this->getCovers($articles);
        if ($format === 'members'){
            return $this->render('articles/members.html.twig', [
                'articles' => $articles,
                'format' => $format,
                'covers' => $covers,
            ]);
        }

        if ($format === 'releases') {
            return $this->render('articles/releases.html.twig', [
                'articles' => $articles,
                'format' => $format,
                'covers' => $covers,
            ]);
        }

        return $this->render('articles/articles.html.twig', [
            'articles' => $articles,
            'format' => $format,
            'covers' => $covers,
        ]);
    }

    /**
     * @Route("/{_locale}/article/{format}/{slug}", requirements={"_locale": "fr|en"}, name="article", methods={"GET"})
     */
    public function article(Request $request)
    {
        $article = $this->article->findOneBy(['slug' => $request->get('slug')]);
        $imageCover = $this->imgRepo->findOneBy(["cover" => true, "article" => $article->getId()]);

        if ($article->getFormat() === "members"){
            return $this->render('article/member.html.twig', [
                'article' => $article,
                'cover' => $imageCover,
            ]);
        }

        if ($article->getFormat() === "releases") {
            return $this->render('article/release.html.twig', [
                'article' => $article,
                'cover' => $imageCover,
            ]);
        }

        return $this->render('article/article.html.twig', [
            'article' => $article,
            'cover' => $imageCover,
        ]);
    }

    /**
     * @Route("/{_locale}/about", name="about", requirements={"_locale": "fr|en"}, methods={"POST", "GET"})
     * @Route("/{_locale}/contact", name="contact", requirements={"_locale": "fr|en"}, methods={"POST", "GET"})
     */
    public function about(Request $request, MailerInterface $mailerInterface)
    {
        $contact = new Contact();
        $contactForm = $this->createForm(ContactType::class, $contact);
        $contactForm->handleRequest($request);

        if ($contactForm->isSubmitted() && $contactForm->isValid()){
            $email = (new TemplatedEmail())
                ->from(new Address('cdlm.free@gmail.com', $contact->getEmail()))
                ->to(new Address('cdlm.free@gmail.com'))
                ->subject("Message de " . $contact->getSurname() . " " . $contact->getName())
                ->htmlTemplate('mailer/contactForm.html.twig')
                ->context([
                    'contact' => $contact,
                ])
                ;
            $mailerInterface->send($email);
            
            $this->addFlash('info', 'Email envoyé! Nous reviendrons vers toi au plus vite.');
        }
        
        if ($request->get('_route') == 'about'){
            return $this->render('about/about.html.twig', [
                'form' => $contactForm->createView(),
            ]);
        }else if ($request->get('_route') == "contact"){
            return $this->render('about/contact.html.twig', [
                'form' => $contactForm->createView(),
            ]);
        }
    }

    /**
     * @Route("/{_locale}/legals", requirements={"_locale": "fr|en"}, name="legals", methods={"GET"})
     */
    public function showLegals()
    {
        return $this->render("legals/legals.html.twig");
    }

    /**
     * @Route("/{_locale}/rgpd", requirements={"_locale": "fr|en"}, name="rgpd", methods={"GET"})
     */
    public function showRGPD()
    {
        return $this->render("legals/rgpd.html.twig");
    }

    private function getCovers($articles)
    {
        $covers = [];
        for($i=0; $i < count($articles); $i++){
            $cover = $this->imgRepo->findOneBy([
                "cover" => true, 
                "article" => $articles[$i]->getId()
                ]);

            if ($cover != null){
                $covers[$i] = [
                    "idArticle" => $articles[$i]->getId(),
                    "covername" => $cover->getName(),
                ];
            }
        }

        return $covers;
    }
}

templates/home_public/index.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    {% set coverArticle %}{{ asset("build/img/Arthur/DSCF6310.jpg") | imagine_filter('300x300') }}{% endset %}
    {% set titleArticle = "Home" %}
    {% set descriptionArticle = "Bienvenue au Chant de la Machine, ce site rassemble l'association organisatrice d'évènements, le label de musique et bien d'autre choses." %}
    {% include 'include/htmlMeta.html.twig' %}
{% endblock %}
{% block body %}
<div class="welcome_view">
  <div class="moving_title" data-aos="fade-down">
    <h1>{% trans %}Hello{% endtrans %}</h1>
    <p>{% trans %}Collectif d’exploration urbaine et musical dans Paris et ses environs{% endtrans %}</p>
  </div>
</div>
<h2 class="part_title"></h2>
<section id="welcome_cards">
{% for article in articles %}
  <div class="welcome_card pulse" data-aos="fade-down">
    <div class="in_card_welcome">
      <a href="{{ path("article", {"format" : article.format, "slug" : article.slug }) }}">
        <div class="col_wel_img">
        {% set hasCover = false %}
        {% if covers != [] %}
          {% for cover in covers %}
            {% if cover.idArticle == article.id %}
              <img src="{{ asset('/upload/pictures/' ~ cover.covername) | imagine_filter('300x300') }}" alt="Photo de l\'article : {{ article.title }}">
              {% set hasCover = true %}
            {% endif %}
          {% endfor %}
        {% endif %}
        {% if hasCover == false %}
          {% if article.imgs|first != "" %}
          <img src="{{ asset('/upload/pictures/' ~ article.imgs|first.name) | imagine_filter('300x300') }}" alt="Photo de l'article : {{ article.title }}">
          {% else %}
          <img src="{{asset('build/img/Arthur/DSCF6226.jpg') | imagine_filter('300x300')}}" alt="Photo de l'article : {{ article.title }}">
          {% endif %}
        {% endif %}
        </div>
        <div class="format_article">
          <p>{{ article.format|trans }}</p>
        </div>
        <div class="col_wel_txt">
          <div class="col_wel_txt_body">
            <h5>{{ article.title }}</h5>
            <p>{{ article.dateEvent|date("m/d/Y") }}
          </div>
        </div>
      </a>
    </div>
  </div>
{% endfor %}
</section>
{% endblock %}

templates/home_public/member.html.twig
{% extends 'base.html.twig' %}
{% block header %}
{% include 'article/meta.html.twig' %}
{% endblock %}
{% block style %}
<link rel="stylesheet" href="/css/label.css">
<link rel="stylesheet" href="/css/label900px.css">
<link rel="stylesheet" href="/css/label600px.css">
{% endblock %}
{% block body %}
<section id="member">
    <div id="title_minwidth"></div>
    <aside id="member_picture">
        <figure>
            {% include 'article/cover.html.twig' %}
            <figcaption id="artist_release_figcaption">
            <div class="contact_socials">
                <a href="mailto:cdlm-free@gmail.com" class="socials_logo"><img src="/img/envelope-open-text-solid.svg" alt="logo email"></a>
                {% if article.socialNetwork.soundcloud != null %}
                <a href="{{ article.socialNetwork.soundcloud }}" target="blank" class="socials_logo"><img src="/img/soundcloud-brands.svg" alt="logo soundcloud"></a>
                {% endif %}
                {% if article.socialNetwork.facebook != null %}
                <a href="{{ article.socialNetwork.facebook }}" target="blank" class="socials_logo"><img src="/img/facebook-square-brands.svg" alt="logo facebook"></a>
                {% endif %}
                {% if article.socialNetwork.instagram != null %}
                <a href="{{ article.socialNetwork.instagram }}" target="blank" class="socials_logo"><img src="/img/instagram-brands.svg" alt="logo instagram"></a>
                {% endif %}
            </div>
            {% if is_granted('ROLE_ADMIN') %}
            {% include 'include/datetimeArticle.html.twig' with { "article": article }%}
            <a href="{{ path("editPost", { "id" : article.id }) }}" class="a_btn btn_modify">Modifier</a>
            {% endif %}
            </figcaption>
        </figure>
    </aside>
    <article id="member_text_soundcloud">
        <h1>{{article.title}}</h1>
        <div class="text">{{article.text|raw}}</div>
        {% if article.apiData != null %}
            <h2>{% trans %}Musique{% endtrans %}</h2>
            <div class="widget_SC">
                {% for sound in article.apiData %}
                <div id="sound[{{loop.index0}}]"></div>
                {% endfor %}
            </div>
        {% endif %}
        {% if article.imgs.snapshot != null %}
            <h2>{% trans %}Images{% endtrans %}</h2>
            <div class="hes-gallery member_images">
            {% for image in article.imgs %}
                <img src="{{ asset('/upload/pictures/' ~ image.name) | imagine_filter('200x150') }}" data-fullsize="{{ asset('/upload/pictures/' ~ image.name) }}"  alt="Photo {{image.id}} de l'article : {{ article.title }}">
            {% endfor %}
            </div>
        {% endif %}
    </article>
</section>
{% endblock %}
{% block javascripts %}
<script src="https://unpkg.com/hes-gallery/dist/hes-gallery.min.js"></script>
<script type="text/javascript" src="/js/movingElt.js"></script>
{% include 'include/soundcloudPlayerJs.html.twig' with {"sounds": article.apiData} %}
<script type="text/javascript">
let moveTitle = new movingElt(
    document.querySelector("#member_text_soundcloud h1"), 
    document.getElementById("title_minwidth"), 
    600
    );
moveTitle.init();

let moveDate = new movingElt(
    document.getElementById("datetime_article"), 
    document.getElementById("member_text_soundcloud"), 
    600
    );
moveDate.init();
</script>
{% endblock %}

templates/home_public/release.html.twig
{% extends 'base.html.twig' %}
{% block title %}<title>{{article.text[:200]|striptags }}</title>{% endblock %}
{% block header %}
{% include 'article/meta.html.twig' %}
{% endblock %}
{% block style %}
<link rel="stylesheet" href="/css/label.css">
<link rel="stylesheet" href="/css/label900px.css">
<link rel="stylesheet" href="/css/label600px.css">
{% endblock %}
{% block body %}
<section id="release">
    <div id="title_minwidth"></div>
    <aside id="member_picture">
        <figure>
            {% include 'article/cover.html.twig' %}
            <figcaption id="artist_release_figcaption">
            <div class="contact_socials">
                <a href="mailto:cdlm-free@gmail.com" class="socials_logo"><img src="/img/envelope-open-text-solid.svg" alt="logo email"></a>
            </div>
            {% if is_granted('ROLE_ADMIN') %}
            {% include 'include/datetimeArticle.html.twig' with { "article": article }%}
            <a href="{{ path("editPost", { "id" : article.id }) }}" class="a_btn btn_modify">Modifier</a>
            {% endif %}
            </figcaption>
        </figure>
    </aside>
    <article id="member_text_soundcloud">
        <h1>{{article.title}}</h1>
        <div class="text">{{article.text|raw}}</div>
        {% if article.apiData != null %}
            <h2>{% trans %}Musique{% endtrans %}</h2>
            <div class="widget_SC">
                {% for sound in article.apiData %}
                <div id="sound[{{loop.index0}}]"></div>
                {% endfor %}
            </div>
        {% endif %}
        {% if article.imgs.snapshot != null %}
            <h2>{% trans %}Images{% endtrans %}</h2>
            <div class="hes-gallery member_images">
            {% for image in article.imgs %}
                    <img src="{{ asset('/upload/pictures/' ~ image.name) | imagine_filter('200x150') }}" data-fullsize="{{ asset('/upload/pictures/' ~ image.name) }}" alt="Photo {{image.id}} de l'article : {{ article.title }}">
            {% endfor %}
            </div>
        {% endif %}
    </article>
</section>
{% endblock %}
{% block javascripts %}
<script src="https://unpkg.com/hes-gallery/dist/hes-gallery.min.js"></script>
<script type="text/javascript" src="/js/movingElt.js"></script>
{% include 'include/soundcloudPlayerJs.html.twig' with {"sounds": article.apiData} %}
<script type="text/javascript">
let moveTitle = new movingElt(
    document.querySelector("#member_text_soundcloud h1"), 
    document.getElementById("title_minwidth"), 
    600
    );
moveTitle.init();

let moveDate = new movingElt(
    document.getElementById("datetime_article"), 
    document.getElementById("member_text_soundcloud"), 
    600
    );
moveDate.init();
</script>
{% endblock %}